package reika.rotarycraft;

import com.mojang.serialization.MapCodec;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.Registries;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.gametest.framework.GameTestInstance;
import net.minecraft.gametest.framework.TestData;
import net.minecraft.gametest.framework.TestEnvironmentDefinition;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Rotation;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.neoforged.neoforge.event.RegisterGameTestsEvent;
import net.neoforged.neoforge.registries.DeferredRegister;

import reika.rotarycraft.blockentities.engine.BlockEntityHydroEngine;
import reika.rotarycraft.blockentities.processing.BlockEntityExtractor;
import reika.rotarycraft.blockentities.production.BlockEntityBedrockBreaker;
import reika.rotarycraft.blockentities.production.BlockEntityFermenter;
import reika.rotarycraft.data.RoCTestStructureProvider;
import reika.rotarycraft.registry.RotaryBlocks;

import java.util.List;
import java.util.function.Consumer;

/**
 * In-world game tests, runnable headless via {@code gradlew :RotaryCraft:runGameTest} or
 * interactively with {@code /test runall} (the {@code rotarycraft} namespace is enabled in
 * build.gradle). Each runs on the {@code rotarycraft:test_arena} structure — a 9×6×9
 * stone-floored box generated by {@link RoCTestStructureProvider}.
 *
 * <p>NeoForge 26.1's {@code RegisterGameTestsEvent} only registers {@link GameTestInstance}s,
 * and the vanilla {@code FunctionGameTestInstance} resolves its body through the
 * {@code TEST_FUNCTION} registry — which freezes before mod construction, so a mod can't add to
 * it. {@link DirectInstance} sidesteps that by holding the test body directly.</p>
 *
 * <p>The {@code TEST_INSTANCE} registry is network-synced (its entries are serialized to the
 * client during the login handshake), so {@link DirectInstance} must expose a real,
 * registry-backed {@link MapCodec} via {@link DirectInstance#codec()} — registered in
 * {@link #TEST_INSTANCE_TYPES}. The codec round-trips the serialisable {@link TestData}; the
 * decoded (client-side) instance carries a no-op body since clients never run the test.</p>
 */
public final class RotaryGameTests {

    private RotaryGameTests() {}

    private static final BlockPos TEST_POS = new BlockPos(4, 1, 4);

    /** Codec types for our in-code {@link GameTestInstance}s; this registry is network-synced. */
    public static final DeferredRegister<MapCodec<? extends GameTestInstance>> TEST_INSTANCE_TYPES =
            DeferredRegister.create(Registries.TEST_INSTANCE_TYPE, RotaryCraft.MODID);

    static {
        TEST_INSTANCE_TYPES.register("direct", () -> DirectInstance.CODEC);
    }

    public static void onRegisterGameTests(RegisterGameTestsEvent event) {
        Holder<TestEnvironmentDefinition<?>> env = event.registerEnvironment(
                Identifier.fromNamespaceAndPath(RotaryCraft.MODID, "default"),
                new TestEnvironmentDefinition.AllOf(List.of()));

        register(event, env, "fermenter_places", 40,
                h -> placesAndTicks(h, RotaryBlocks.FERMENTER.get(), BlockEntityFermenter.class));
        register(event, env, "extractor_places", 40,
                h -> placesAndTicks(h, RotaryBlocks.EXTRACTOR.get(), BlockEntityExtractor.class));
        register(event, env, "bedrock_breaker_places", 40,
                h -> placesAndTicks(h, RotaryBlocks.BEDROCK_BREAKER.get(), BlockEntityBedrockBreaker.class));
        register(event, env, "hydro_engine_places", 40,
                h -> placesAndTicks(h, RotaryBlocks.HYDRO_ENGINE.get(), BlockEntityHydroEngine.class));
    }

    /**
     * Places the machine block, asserts its BlockEntity is the expected type (catches wrong-BE-type
     * registration), and lets it tick for a second to surface ticker / lifecycle NPEs.
     */
    private static <T extends BlockEntity> void placesAndTicks(GameTestHelper helper, Block block, Class<T> beType) {
        helper.setBlock(TEST_POS, block);
        helper.getBlockEntity(TEST_POS, beType); // throws on missing / wrong type
        helper.runAfterDelay(20, () -> {
            helper.getBlockEntity(TEST_POS, beType); // still alive and correct after ticking
            helper.succeed();
        });
    }

    private static void register(RegisterGameTestsEvent event, Holder<TestEnvironmentDefinition<?>> env,
                                 String name, int maxTicks, Consumer<GameTestHelper> body) {
        Identifier id = Identifier.fromNamespaceAndPath(RotaryCraft.MODID, name);
        TestData<Holder<TestEnvironmentDefinition<?>>> data =
                new TestData<>(env, RoCTestStructureProvider.ARENA, maxTicks, 0, true, Rotation.NONE);
        event.registerTest(id, new DirectInstance(data, body));
    }

    /**
     * A {@link GameTestInstance} that carries its test body as a plain {@link Consumer} instead of
     * a {@code TEST_FUNCTION} registry key. {@link #codec()} is never exercised because these are
     * registered as live objects (not serialized from a datapack) on the headless test server.
     */
    private static final class DirectInstance extends GameTestInstance {
        /**
         * Round-trips the serialisable {@link TestData}. Encoding reads the live instance's data;
         * decoding (only ever on a sync-receiving client) yields a no-op body — clients don't run
         * tests, they just need the registry entry to deserialise without crashing.
         */
        static final MapCodec<DirectInstance> CODEC =
                TestData.CODEC.xmap(data -> new DirectInstance(data, h -> {}), inst -> inst.info);

        private final TestData<Holder<TestEnvironmentDefinition<?>>> info;
        private final Consumer<GameTestHelper> body;

        DirectInstance(TestData<Holder<TestEnvironmentDefinition<?>>> info, Consumer<GameTestHelper> body) {
            super(info);
            this.info = info;
            this.body = body;
        }

        @Override
        public void run(GameTestHelper helper) {
            body.accept(helper);
        }

        @Override
        public MapCodec<? extends GameTestInstance> codec() {
            return CODEC;
        }

        @Override
        protected MutableComponent typeDescription() {
            return Component.literal("rotarycraft direct test");
        }
    }
}
