package reika.rotarycraft.renders.item;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.serialization.Codec;
import com.mojang.serialization.MapCodec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.client.model.geom.EntityModelSet;
import net.minecraft.client.renderer.SubmitNodeCollector;
import net.minecraft.client.renderer.special.SpecialModelRenderer;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.component.DataComponents;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.component.CustomData;
import net.minecraft.resources.Identifier;
import org.joml.Vector3fc;
import reika.rotarycraft.RotaryCraft;
import reika.rotarycraft.base.RotaryModelBase;
import reika.rotarycraft.base.blocks.entity.transmission.BlockGearbox;
import reika.rotarycraft.client.MachineModels;
import reika.rotarycraft.models.animated.Gearbox4Model;
import reika.rotarycraft.models.animated.Gearbox8Model;
import reika.rotarycraft.models.animated.Gearbox16Model;
import reika.rotarycraft.registry.MachineRegistry;
import reika.rotarycraft.registry.RotaryModelLayers;

import java.util.Locale;
import java.util.function.Consumer;

/** Minecraft 26.3 machine item renderer. Display transforms are generated by RoCModelProvider. */
public class MachineItemRenderer implements SpecialModelRenderer<MachineItemRenderer.ItemState> {

    public static final Identifier ID = Identifier.fromNamespaceAndPath(RotaryCraft.MODID, "machine");

    private final MachineItemGeometry geometry;
    private final MachineItemGeometry bedrockGeometry;
    private final Identifier texture;
    private final Identifier bedrockTexture;
    private final MachineRegistry machine;

    public enum ItemState { NORMAL, BEDROCK }

    public MachineItemRenderer(MachineRegistry machine, RotaryModelBase model, Identifier texture) {
        this.geometry = MachineItemGeometry.bake(machine, model);
        this.bedrockGeometry = machine == MachineRegistry.HYDRO_ENGINE
                ? MachineItemGeometry.bake(machine, model, true) : geometry;
        this.texture = texture;
        this.machine = machine;
        this.bedrockTexture = switch (machine) {
            case HYDRO_ENGINE -> Unbaked.texture("engine/bedhydrotex.png");
            case COIL, CREATIVE_COIL -> Unbaked.texture("transmission/coiltex_bed.png");
            case SPLITTER -> Unbaked.texture("bedsplittertex.png");
            default -> texture;
        };
    }

    @Override
    public ItemState extractArgument(ItemStack stack) {
        if (machine == MachineRegistry.CREATIVE_COIL) return ItemState.BEDROCK;
        if (machine != MachineRegistry.HYDRO_ENGINE && machine != MachineRegistry.COIL
                && machine != MachineRegistry.SPLITTER) return ItemState.NORMAL;
        var tag = stack.getOrDefault(DataComponents.CUSTOM_DATA, CustomData.EMPTY).copyTag();
        // Hydro's original placer used "bed"; the modern saved machine data uses "bedrock".
        return tag.getBooleanOr("bedrock", false)
                || (machine == MachineRegistry.HYDRO_ENGINE && tag.getBooleanOr("bed", false))
                ? ItemState.BEDROCK : ItemState.NORMAL;
    }

    @Override
    public void submit(ItemState argument, PoseStack poseStack, SubmitNodeCollector collector, int lightCoords,
                       int overlayCoords, boolean hasFoil, int outlineColor) {
        MachineItemGeometry selected = argument == ItemState.BEDROCK ? bedrockGeometry : geometry;
        Identifier selectedTexture = argument == ItemState.BEDROCK ? bedrockTexture : texture;
        collector.submitCustomGeometry(poseStack, hasFoil ? RenderTypes.itemCutoutGlint(selectedTexture) : RenderTypes.entityCutout(selectedTexture),
                (pose, buffer) -> selected.draw(pose, buffer, lightCoords, overlayCoords, -1));
        if (outlineColor != 0)
            collector.submitCustomGeometry(poseStack, RenderTypes.outline(selectedTexture),
                    (pose, buffer) -> selected.draw(pose, buffer, lightCoords, overlayCoords, outlineColor));
    }

    @Override
    public void getExtents(Consumer<Vector3fc> output) {
        // SpecialModelWrapper measures the same immutable vertices submitted for rendering.
        geometry.getExtents(output);
        if (bedrockGeometry != geometry) bedrockGeometry.getExtents(output);
    }

    /** The variant identifies the registered block, preserving ratio and material after baking. */
    public record Unbaked(String machine, String variant) implements SpecialModelRenderer.Unbaked<ItemState> {
        public static final MapCodec<Unbaked> MAP_CODEC = RecordCodecBuilder.mapCodec(i -> i.group(
                Codec.STRING.fieldOf("machine").forGetter(Unbaked::machine),
                Codec.STRING.optionalFieldOf("variant", "").forGetter(Unbaked::variant)
        ).apply(i, Unbaked::new));

        public Unbaked(String machine) {
            this(machine, "");
        }

        @Override
        public MapCodec<? extends SpecialModelRenderer.Unbaked<ItemState>> type() {
            return MAP_CODEC;
        }

        @Override
        public MachineItemRenderer bake(SpecialModelRenderer.BakingContext context) {
            MachineRegistry m;
            try {
                m = MachineRegistry.valueOf(machine.toUpperCase(Locale.ROOT));
            } catch (IllegalArgumentException e) {
                RotaryCraft.LOGGER.warn("Unknown machine '{}' in special model renderer", machine);
                return null;
            }
            if (!MachineModels.has(m)) {
                RotaryCraft.LOGGER.warn("MachineRegistry.{} has no model registered", m);
                return null;
            }
            String blockPath = variant.isEmpty() ? BuiltInRegistries.BLOCK.getKey(m.getBlockState().getBlock()).getPath() : variant;
            RotaryModelBase model = bakeModel(m, blockPath, context.entityModelSet());
            return new MachineItemRenderer(m, model, resolveTexture(m, blockPath, model));
        }

        public static RotaryModelBase bakeModel(MachineRegistry machine, String variant, EntityModelSet models) {
            if (machine == MachineRegistry.GEARBOX) {
                if (variant.endsWith("_4x")) return new Gearbox4Model(models.bakeLayer(RotaryModelLayers.GEARBOX_4));
                if (variant.endsWith("_8x")) return new Gearbox8Model(models.bakeLayer(RotaryModelLayers.GEARBOX_8));
                if (variant.endsWith("_16x")) return new Gearbox16Model(models.bakeLayer(RotaryModelLayers.GEARBOX_16));
            }
            return MachineModels.get(machine).apply(models);
        }

        public static Identifier resolveTexture(MachineRegistry machine, String variant, RotaryModelBase model) {
            String suffix = switch (machine) {
                case WOOD_SHAFT -> "w";
                case STONE_SHAFT -> "s";
                case HSLA_SHAFT -> "";
                case TUNGSTEN_SHAFT -> "t";
                case DIAMOND_SHAFT -> "d";
                case BEDROCK_SHAFT -> "b";
                default -> null;
            };
            if (suffix != null) return texture("transmission/shaft/shafttex" + suffix + ".png");
            if (machine == MachineRegistry.SHAFT_CROSS || machine == MachineRegistry.SHAFT_MERGE)
                return texture("transmission/shaft/crosstex.png");
            if (machine == MachineRegistry.GEARBOX) {
                var block = BuiltInRegistries.BLOCK.getValue(Identifier.fromNamespaceAndPath(RotaryCraft.MODID, variant));
                if (block instanceof BlockGearbox gearbox)
                    return texture("transmission/gear/" + gearbox.type.getBaseGearboxTexture());
            }
            if (machine == MachineRegistry.FLYWHEEL) {
                String material = variant.substring(0, variant.length() - "_flywheel".length());
                if (material.equals("depleted_uranium")) material = "depletedu";
                return texture("transmission/flywheel/" + material + ".png");
            }
            if (machine == MachineRegistry.CREATIVE_COIL) return texture("transmission/coiltex_bed.png");
            return model.getTexture();
        }

        private static Identifier texture(String name) {
            return Identifier.fromNamespaceAndPath(RotaryCraft.MODID, "textures/blockentitytex/" + name);
        }
    }
}
