/*******************************************************************************
 * @author Reika Kalseki
 *
 * Copyright 2017
 *
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 24/03/2013 6:26:43 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package reika.rotarycraft.models;
import net.minecraft.world.level.block.entity.BlockEntity;
import reika.rotarycraft.RotaryCraft;
import reika.rotarycraft.base.RotaryModelBase;
import net.minecraft.client.renderer.texture.OverlayTexture;
import java.util.ArrayList;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.Model;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.rendertype.RenderType;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.entity.BlockEntity;
import reika.rotarycraft.base.RotaryModelBase;

import java.util.ArrayList;


public class VLampModel extends RotaryModelBase {

    /**
     * 1.7.10 {@code RenderLamp} bound {@code LampVertical.png} for the ceiling/floor-mounted
     * floodlight and {@code lamptex.png} for the wall-mounted one; the port had both pointing at
     * {@code lamptex.png}, leaving the shipped vertical texture unused.
     */
    public static final Identifier TEXTURE_LOCATION =
            Identifier.fromNamespaceAndPath(RotaryCraft.MODID, "textures/blockentitytex/lampvertical.png");
    //fields
    public final ModelPart shape1;
    public final ModelPart shape2;
    public final ModelPart shape3;
    public final ModelPart shape4;
    public final ModelPart shape5;
    public final ModelPart shape6;
    public final ModelPart shape7;
    public final ModelPart shape8;
    public final ModelPart shape9;
    public final ModelPart shape10;
    public final ModelPart shape11;
    public final ModelPart shape12;
    public final ModelPart shape13;
    public final ModelPart shape14;
    public final ModelPart shape15;
    public final ModelPart shape16;
    public final ModelPart shape17;
    public final ModelPart shape17b;
    public final ModelPart shape18;
    public final ModelPart shape18b;
    public final ModelPart shape19;

    public VLampModel(ModelPart root) {
        super(root, RenderTypes::entitySolid);

        this.shape1 = root.getChild("shape1");
        this.shape2 = root.getChild("shape2");
        this.shape3 = root.getChild("shape3");
        this.shape4 = root.getChild("shape4");
        this.shape5 = root.getChild("shape5");
        this.shape6 = root.getChild("shape6");
        this.shape7 = root.getChild("shape7");
        this.shape8 = root.getChild("shape8");
        this.shape9 = root.getChild("shape9");
        this.shape10 = root.getChild("shape10");
        this.shape11 = root.getChild("shape11");
        this.shape12 = root.getChild("shape12");
        this.shape13 = root.getChild("shape13");
        this.shape14 = root.getChild("shape14");
        this.shape15 = root.getChild("shape15");
        this.shape16 = root.getChild("shape16");
        this.shape17 = root.getChild("shape17");
        this.shape17b = root.getChild("shape17b");
        this.shape18 = root.getChild("shape18");
        this.shape18b = root.getChild("shape18b");
        this.shape19 = root.getChild("shape19");
        // Part offsets live in createLayer() (PartPose), the single source of truth;
        // they used to be re-applied here on the baked ModelPart.

    }

    public static LayerDefinition createLayer() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();

        partdefinition.addOrReplaceChild("shape1", CubeListBuilder.create().texOffs(0, 0)
                .addBox(0F, 0F, 0F, 16, 1, 16)
                .mirror(), PartPose.offset(-8, 23, -8));

        partdefinition.addOrReplaceChild("shape2", CubeListBuilder.create().texOffs(67, 30)
                .addBox(0F, 0F, 0F, 14, 14, 5)
                .mirror(), PartPose.offsetAndRotation(-7, 16, 7, -1.570796F, 0, 0));

        partdefinition.addOrReplaceChild("shape3", CubeListBuilder.create().texOffs(0, 58)
                .addBox(0F, 0F, 0F, 2, 12, 4)
                .mirror(), PartPose.offsetAndRotation(-6, 12, 6, -1.570796F, 0, 0));

        partdefinition.addOrReplaceChild("shape4", CubeListBuilder.create().texOffs(0, 58)
                .addBox(0F, 0F, 0F, 2, 12, 4)
                .mirror(), PartPose.offsetAndRotation(4, 12, 6, -1.570796F, 0, 0));

        partdefinition.addOrReplaceChild("shape5", CubeListBuilder.create().texOffs(0, 52)
                .addBox(0F, 0F, 0F, 8, 2, 4)
                .mirror(), PartPose.offsetAndRotation(-4, 12, 6, -1.570796F, 0, 0));

        partdefinition.addOrReplaceChild("shape6", CubeListBuilder.create().texOffs(0, 52)
                .addBox(0F, 0F, 0F, 8, 2, 4)
                .mirror(), PartPose.offsetAndRotation(-4, 12.1F, -4, -1.570796F, 0, 0));

        partdefinition.addOrReplaceChild("shape7", CubeListBuilder.create().texOffs(12, 58)
                .addBox(0F, 0F, 0F, 1, 10, 2)
                .mirror(), PartPose.offsetAndRotation(4, 10, 5, -1.570796F, 0, 0));

        partdefinition.addOrReplaceChild("shape8", CubeListBuilder.create().texOffs(12, 58)
                .addBox(0F, 0F, 0F, 1, 10, 2)
                .mirror(), PartPose.offsetAndRotation(-5, 10, 5, -1.570796F, 0, 0));

        partdefinition.addOrReplaceChild("shape9", CubeListBuilder.create().texOffs(32, 54)
                .addBox(0F, 0F, 0F, 8, 1, 2)
                .mirror(), PartPose.offsetAndRotation(-4, 10, 5, -1.570796F, 0, 0));

        partdefinition.addOrReplaceChild("shape10", CubeListBuilder.create().texOffs(32, 54)
                .addBox(0F, 0F, 0F, 8, 1, 2)
                .mirror(), PartPose.offsetAndRotation(-4, 10.1F, -4, -1.570796F, 0, 0));

        partdefinition.addOrReplaceChild("shape11", CubeListBuilder.create().texOffs(64, 49)
                .addBox(0F, 0F, 0F, 15, 15, 2)
                .mirror(), PartPose.offsetAndRotation(-7.5F, 21, 7.5F, -1.570796F, 0, 0));

        partdefinition.addOrReplaceChild("shape12", CubeListBuilder.create().texOffs(32, 57)
                .addBox(0F, 0F, 0F, 8, 1, 2)
                .mirror(), PartPose.offsetAndRotation(-4, 10, 4, -1.570796F, 0, 0));

        partdefinition.addOrReplaceChild("shape13", CubeListBuilder.create().texOffs(32, 57)
                .addBox(0F, 0F, 0F, 8, 1, 2)
                .mirror(), PartPose.offsetAndRotation(-4, 10.1F, -3, -1.570796F, 0, 0));

        partdefinition.addOrReplaceChild("shape14", CubeListBuilder.create().texOffs(20, 24)
                .addBox(0F, 0F, 0F, 1, 6, 2)
                .mirror(), PartPose.offsetAndRotation(-4, 10, 3, -1.56207F, 0, -0.0174533F));

        partdefinition.addOrReplaceChild("shape15", CubeListBuilder.create().texOffs(20, 24)
                .addBox(0F, 0F, 0F, 1, 6, 2)
                .mirror(), PartPose.offsetAndRotation(3, 10, 3, -1.56207F, 0, 0));

        partdefinition.addOrReplaceChild("shape16", CubeListBuilder.create().texOffs(-1, 45)
                .addBox(0F, 0F, 0F, 6, 6, 1)
                .mirror(), PartPose.offsetAndRotation(-3, 11, 3, -1.570796F, 0, 0));

        partdefinition.addOrReplaceChild("shape17", CubeListBuilder.create().texOffs(0, 84)
                .addBox(0F, 0F, 0F, 4, 7, 1)
                .mirror(), PartPose.offsetAndRotation(-2, 10, -6, -0.1396263F, 0, 0));

        partdefinition.addOrReplaceChild("shape17b", CubeListBuilder.create().texOffs(0, 84)
                .addBox(0F, 0F, 0F, 4, 7, 1)
                .mirror(), PartPose.offsetAndRotation(-2, 10, 5, 0.1396263F, 0, 0));

        partdefinition.addOrReplaceChild("shape18", CubeListBuilder.create().texOffs(0, 84)
                .addBox(0F, 0F, 0F, 1, 7, 4)
                .mirror(), PartPose.offsetAndRotation(5, 10, -2, 0, 0, -0.1396263F));

        partdefinition.addOrReplaceChild("shape18b", CubeListBuilder.create().texOffs(0, 84)
                .addBox(0F, 0F, 0F, 1, 7, 4).mirror()
                .mirror(), PartPose.offsetAndRotation(-6, 10, -2, 0, 0, 0.1396263F));

        partdefinition.addOrReplaceChild("shape19", CubeListBuilder.create().texOffs(0, 96)
                .addBox(0F, 0F, 0F, 8, 2, 8)
                .mirror(), PartPose.offset(-4, 8, -4));

        return LayerDefinition.create(meshdefinition, 128, 128);
    }

    @Override
    public void renderAll(PoseStack stack, VertexConsumer pBuffer, int pPackedLight, BlockEntity te, ArrayList<?> li, float phi, float theta) {
        boolean beam = (Boolean) li.get(0);
        shape1.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        shape2.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        shape3.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        shape4.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        shape5.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        shape6.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        shape7.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        shape8.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        shape9.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        shape10.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        shape11.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        shape12.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        shape13.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        shape14.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        shape15.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        shape16.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        if (beam) {
            shape17.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
            shape17b.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
            shape18.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
            shape18b.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
            shape19.render(stack, pBuffer, pPackedLight, OverlayTexture.NO_OVERLAY);
        }
    }
    @Override
    public Identifier getTexture() {
        return TEXTURE_LOCATION;
    }
}

